=== Dragolex01/Dragolex01.github.io/PÁGINA WEB/XML/HISTORIA/HistoriaDTD.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT historia (ford, mustang) >
<!ELEMENT ford (titulo, fecha_fundada, fundador, nacimiento, muerte, origen, primer_coche) >
<!ELEMENT mustang (titulo, fecha_fundada, fundador, nacimiento, muerte, origen, primer_coche) >

<!ELEMENT titulo (#PCDATA)>
<!ELEMENT fecha_fundada (#PCDATA)>
<!ELEMENT fundador (#PCDATA)>
<!ELEMENT nacimiento (#PCDATA)>
<!ELEMENT muerte (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT primer_coche (#PCDATA) >

=== Dragolex01/Dragolex01.github.io/PÁGINA WEB/XML/HISTORIA/Historia.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="HistoriaXSL.xsl"?>
<!DOCTYPE historia SYSTEM "HistoriaDTD.dtd">
<historia xmlns:p="http://www.prueba.es/historia" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.prueba.es/catalogo HistoriaXSD.xsd">
    <ford>
        <titulo>FORD</titulo>
        <fecha_fundada>1903</fecha_fundada>
        <fundador>Henry Ford</fundador>
        <nacimiento>30 de julio de 1863</nacimiento>
        <muerte>7 de abril de 1947</muerte>
        <origen>estadounidense</origen>
        <primer_coche>Ford T.</primer_coche>
    </ford>
    <mustang>
        <titulo>MUSTANG</titulo>
        <fecha_fundada>1964</fecha_fundada>
        <fundador>Pascual Ros</fundador>
        <nacimiento>15 de agosto de 1915</nacimiento>
        <muerte>12 de noviembre de 2009</muerte>
        <origen>estadounidense</origen>
        <primer_coche>Wimbledon White</primer_coche>
    </mustang>
</historia>
